### ISSUE TITLE
Error on swan setup

### ISSUE THREAD

**Issue by ghost** [SpoonX/swan-cli#12]
I'm trying to use swan setup as follows:
`swan setup spoonx/aurelia-todo`

But I get the following error:

```
- Forking project.Repository not forked after 30 retries. Please try running the same command again.

</3 Unable to fork spoonx/aurelia-todo.
Does the personal access token have full access to repo?
```

I've granted the access token the repo permissions.
What could be the reason?

**Comment by RWOverdijk** [comment]
@kst83 We'll take a look. For the time being, I'd recommend removing the [aurelia-todo](https://github.com/kst83/aurelia-todo) fork.

For our information, could you share your environment info? OS and node version specifically would be very helpful :)

**Comment by ghost** [comment]
Thanks for looking at it.
My OS is Windows and I'm on Node 6.2.1

**Comment by RWOverdijk** [comment]
@kst83 I haven't tested this on windows yet. Is your access token configured? As in, did you run `swan configure`?

**Comment by ghost** [comment]
Yes, I did run it.
I also created a .gitconfig file.

**Comment by RWOverdijk** [comment]
Mhm alright.... It might take a little while, but I'll have a look at this :)

To verify, you installed sails, gulp and jspm **globally**?

**Comment by ghost** [comment]
Yes, they are installed globally

**Comment by VMBindraban** [comment]
@kst83 Which version of Windows do you run?
I tried it on windows 7 and it works.

We renamed the project to `spoonx/swan-example` a couple of days ago.
Can you try `swan setup spoonx/swan-example`?

**Comment by ghost** [comment]
I'm on Windows 10.
Do I need some special settings in .gitconfig maybe?

**Comment by VMBindraban** [comment]
My `.gitconfig` only contains my username and email.

**Comment by VMBindraban** [comment]
@kst83 I got the same issue on Win10. I will take a look at it.

**Comment by VMBindraban** [comment]
@kst83 Do you have your `name` set in the `.gitconfig`? This was the reason why it didn't work for me.

**Comment by ghost** [comment]
Yes, I have it set.
It can be any value, right?

**Comment by VMBindraban** [comment]
@kst83 It must be your username. It will check if `your-username/repo-name` has been forked.

**Comment by ghost** [comment]
Thanks, now its at leas working until "installing server (1/2)".
But I still get </3 Unable to fork spoonx/swan-example after that.

**Comment by VMBindraban** [comment]
@kst83 Can you run `npm install` within the server directory? It seems that npm is giving an error.

**Comment by ghost** [comment]
After adding Python 27 to my path and running "npm config set msvs_version 2015" to match my Visual Studio Express 2015 version, npm install is now running smoothly.

swan setup spoonx/swan-example no works too

thanks for the help!
