### ISSUE TITLE
Ask for username when configuring

### ISSUE THREAD

**Issue by VMBindraban** [SpoonX/swan-cli#19]
The username is not always set in the config of git.
This results into checking `undefiend/repo-name` when using setup.

Ask for git username on configure, show the username if it exists in the config.

**Comment by RWOverdijk** [comment]
Also ask on setup when empty :)

**Comment by VMBindraban** [comment]
Not needed since you _must_ run configure before you are allowed to run setup.

**Comment by RWOverdijk** [comment]
Toppie!
