### ISSUE TITLE
Client skeleton clone ignores chosen protocol

### ISSUE THREAD

**Issue by Kukks** [SpoonX/swan-cli#26]
Upon attempting to create a new project using https, I was getting 

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So I looked at the code a bit and noticed the clientSkeleton var in config was fixed to only ssh. As soon as I switched the string to the https equivalent project creation seems to have worked.

**Comment by doktordirk** [comment]
@RWOverdijk i remember that issue, but wasn.t it fixed?

**Comment by RWOverdijk** [comment]
@VMBindraban Ping.

**Comment by VMBindraban** [comment]
I will take a look at it.

**Comment by RWOverdijk** [comment]
@Kukks This should be fixed :)
