### ISSUE TITLE
What do you get from having Sails and Aurelia in the same stack?

### ISSUE THREAD

**Issue by DamnedScholar** [SpoonX/swan-cli#29]
I'm a dabbler who uses Aurelia as a low-learning-curve framework that I don't have to put a whole bunch of time into, so I'm not super highly educated on the peculiarities of different frameworks, but I know what's out there. In reading through the documentation about SWAN, I haven't been able to find an answer for one specific question. Sails and Aurelia have some functionality overlap and as someone coming from Aurelia, I don't know exactly where they slot together in SWAN. Are there any parts of Aurelia that are being replaced with Sails? Does the SWAN stack accept a site written as a perfectly valid Aurelia site even if it ignores Sails? What does Sails do for me that Aurelia doesn't?

**Comment by AngelMunoz** [comment]
Sails would be working as a backend solution for your Aurelia application, most likely talking to each other via HTTP (either fetch or ajax) requests, aurelia fits as a single page frontend application framework which ls great and easy to use, while sails is a fast and easy way to generate RESTful API's they do actually fit well together, and they serve different purposes

**Comment by RWOverdijk** [comment]
I missed this issue completely, I'm sorry.

Yes, that's exactly true. The stack is a complete bundle consisting of database, api, frontend and a platform.

Longer, more future oriented version:

Swan has been a bit quiet, awaiting the new ORM. The idea is to make an more useful integration that allows you to share some of the characteristics in for instance entities. This requires some thinking though, as client side and server side entities can be completely different. The CLI needs to add convenience to maintain, deploy, update, generate boilerplate code etcetera.

The next version will contain validation, forms, and auto resources (auto entities based on server-side). This would add default behavior to entities with no need to format them. If they require special treatment, simply create the file, and it won't fetch the info from the server.
